services:
  bookingrevamp:
    build: .
    container_name: bookingrevamp_app_restored
    restart: always
    ports:
      - "2580:8080"
    depends_on:
      - postgresdb
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  postgresdb:
    image: postgres:16
    container_name: bookingdatabase_revamp
    restart: always
    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: K7m#Q2x
    ports:
      - "5444:5432"
    volumes:
      - bookingrevamp_restored:/var/lib/postgresql/data

volumes:
  bookingrevamp_restored: