// <auto-generated />
using System;
using BookingRevamp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingRevamp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712102205_AddMoreAmenity1")]
    partial class AddMoreAmenity1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingRevamp.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Основні",
                            Icon = "wifi.png",
                            Name = "Швидкісний WI-FI",
                            Size = "l"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Основні",
                            Icon = "air-conditioner.png",
                            Name = "Кондиціонер",
                            Size = "m"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Основні",
                            Icon = "heating.png",
                            Name = "Опалення",
                            Size = "m"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Основні",
                            Icon = "tv.png",
                            Name = "Телевізор",
                            Size = "m"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Основні",
                            Icon = "generator.png",
                            Name = "Генератор",
                            Size = "m"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Основні",
                            Icon = "elevator.png",
                            Name = "Ліфт",
                            Size = "s"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Спальня",
                            Icon = "wardrobe.png",
                            Name = "Шафа або гардероб",
                            Size = "l"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Спальня",
                            Icon = "bedclothes.png",
                            Name = "Постільна білизна",
                            Size = "l"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Спальня",
                            Icon = "iron.png",
                            Name = "Праска",
                            Size = "m"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Спальня",
                            Icon = "safe.png",
                            Name = "Сейф",
                            Size = "m"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Кухня та харчування",
                            Icon = "kitchen-set.png",
                            Name = "Повністю обладнана кухня",
                            Size = "l"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Кухня та харчування",
                            Icon = "freezer.png",
                            Name = "Холодильник",
                            Size = "m"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Кухня та харчування",
                            Icon = "stove.png",
                            Name = "Плита",
                            Size = "m"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Кухня та харчування",
                            Icon = "oven.png",
                            Name = "Духова піч",
                            Size = "m"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Кухня та харчування",
                            Icon = "coffee-maker.png",
                            Name = "Кавоварка",
                            Size = "m"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Кухня та харчування",
                            Icon = "kettle.png",
                            Name = "Електрочайник",
                            Size = "m"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Кухня та харчування",
                            Icon = "microwave.png",
                            Name = "Мікрохвильова піч",
                            Size = "l"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Ванна кімната та прання",
                            Icon = "separate-bath.png",
                            Name = "Власна ванна кімната",
                            Size = "l"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Ванна кімната та прання",
                            Icon = "shower.png",
                            Name = "Душ",
                            Size = "s"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Ванна кімната та прання",
                            Icon = "bathtub.png",
                            Name = "Ванна",
                            Size = "m"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Ванна кімната та прання",
                            Icon = "washing-machine.png",
                            Name = "Пральна машина",
                            Size = "l"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Ванна кімната та прання",
                            Icon = "towels.png",
                            Name = "Рушники",
                            Size = "m"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Ванна кімната та прання",
                            Icon = "cosmetics.png",
                            Name = "Косметичні засоби",
                            Size = "l"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Територія та вигляд",
                            Icon = "balcony.png",
                            Name = "Балкон",
                            Size = "m"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Територія та вигляд",
                            Icon = "terrace.png",
                            Name = "Тераса",
                            Size = "m"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Територія та вигляд",
                            Icon = "sea-view.png",
                            Name = "Вид на море",
                            Size = "m"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Територія та вигляд",
                            Icon = "mountain-view.png",
                            Name = "Вид на гори",
                            Size = "m"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Територія та вигляд",
                            Icon = "closed-area.png",
                            Name = "Закрита тереторія",
                            Size = "l"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Територія та вигляд",
                            Icon = "garden.png",
                            Name = "Сад",
                            Size = "s"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Для дітей",
                            Icon = "baby-bed.png",
                            Name = "Дитяче ліжечко",
                            Size = "m"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Для дітей",
                            Icon = "play-area.png",
                            Name = "Ігрова зона",
                            Size = "m"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Додаткові можливості",
                            Icon = "cleaning.png",
                            Name = "Прибирання",
                            Size = "m"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Додаткові можливості",
                            Icon = "breakfast.png",
                            Name = "Сніданок включено",
                            Size = "l"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Безпека",
                            Icon = "security-camera.png",
                            Name = "Відеоспостереження",
                            Size = "l"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Безпека",
                            Icon = "bunker.png",
                            Name = "Укриття",
                            Size = "m"
                        });
                });

            modelBuilder.Entity("BookingRevamp.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardLast4")
                        .HasColumnType("text");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Guests")
                        .HasColumnType("integer");

                    b.Property<string>("LiqPayOrderId")
                        .HasColumnType("text");

                    b.Property<string>("LiqPayTransactionId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookingRevamp.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("BookingRevamp.Models.PartnerApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcceptTerms")
                        .HasColumnType("boolean");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportPath")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PartnerApplications");
                });

            modelBuilder.Entity("BookingRevamp.Models.PendingPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Guests")
                        .HasColumnType("integer");

                    b.Property<string>("LiqPayOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PendingPayments");
                });

            modelBuilder.Entity("BookingRevamp.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AllowChildren")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowPets")
                        .HasColumnType("boolean");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("integer");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("numeric");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("BookingRevamp.Models.PropertyAmenity", b =>
                {
                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("AmenityId")
                        .HasColumnType("integer");

                    b.HasKey("PropertyId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("PropertyAmenities");
                });

            modelBuilder.Entity("BookingRevamp.Models.PropertyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");
                });

            modelBuilder.Entity("BookingRevamp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BookingRevamp.Models.Booking", b =>
                {
                    b.HasOne("BookingRevamp.Models.Property", "Property")
                        .WithMany("Bookings")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingRevamp.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingRevamp.Models.Favorite", b =>
                {
                    b.HasOne("BookingRevamp.Models.Property", "Property")
                        .WithMany("Favorites")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingRevamp.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingRevamp.Models.PartnerApplication", b =>
                {
                    b.HasOne("BookingRevamp.Models.User", "User")
                        .WithMany("PartnerApplications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingRevamp.Models.Property", b =>
                {
                    b.HasOne("BookingRevamp.Models.User", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BookingRevamp.Models.PropertyAmenity", b =>
                {
                    b.HasOne("BookingRevamp.Models.Amenity", "Amenity")
                        .WithMany("PropertyAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingRevamp.Models.Property", "Property")
                        .WithMany("Amenities")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("BookingRevamp.Models.PropertyImage", b =>
                {
                    b.HasOne("BookingRevamp.Models.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("BookingRevamp.Models.Amenity", b =>
                {
                    b.Navigation("PropertyAmenities");
                });

            modelBuilder.Entity("BookingRevamp.Models.Property", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Bookings");

                    b.Navigation("Favorites");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("BookingRevamp.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Favorites");

                    b.Navigation("PartnerApplications");

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
